# InboundEngine 設定ファイル

common:
  log_level: "INFO"
  file_paths:
    google_key_file: "gspread-key.json"
  logs_directory: "logs" 


# 自動投稿Bot設定
auto_post_bot:
  # Discord通知設定（メイン通知システム）
  discord_notification:
    enabled: true
    webhook_url: "https://discord.com/api/webhooks/1378206571556765707/8_9FQToOU1qwc7xESSfJlizX9Xx-Ls1NxZQMF0Xht9wuTR9FozY9PihorKn0RromKqRp"
    notify_daily_schedule_summary: true
  schedule_settings:
    start_hour: 10
    end_hour: 22
    min_interval_minutes: 1
    schedule_file: "schedule.txt"
    executed_file: "executed.txt"
    test_schedule_file: "test_schedule.txt"  # ← テスト用スケジュールファイル 
    test_executed_file: "test_executed.txt" # ← テスト用実行済み記録ファイル 

  # 他の通知設定を無効化
  line_notify:
    enabled: false
    access_token: ""

  email_notification:
    enabled: false

  slack_webhook_url: ""
  sheet_name: "投稿ストック"
  columns: ["ID", "本文", "文字数", "画像/動画URL", "最終投稿日時", "投稿可能", "投稿済み回数"]
  
  google_sheets_source:
    enabled: true
    spreadsheet_id: "1lgCn5iAiFT9PSr3vA3Tp1SePe0g3B9Xe1ppsr8bn2FA"
    worksheet_name: "都内メンエス"

  posting_settings:
    posts_per_account: 5  # 1日の投稿回数
    max_post_count: 100  # 全体の最大投稿回数
    post_interval_seconds: 60  # 投稿間隔を5分（300秒）に延長
  
  
  media_settings:
    download_timeout: 60
    error_message_max_length: 100
    temp_file_cleanup: true
  
  text_settings:
    thread_padding: 10
    content_preview_length: 50
  
  twitter_accounts:
    - account_id: "ZaikerLong"
      consumer_key: "xAPh3lRibyp8qEqhXSlCPi9ls"
      consumer_secret: "EtWUYJRfXw37ZQyVP5LwQog13xi2UV3FYRvSWmYx4OF5zhg22j"
      access_token: "1332761771279601672-QZXhMnpVtjEWecoLMM40QmPCENzY0x"
      access_token_secret: "ZySI4nVscSfMjdGGpcOyOYbvRGePF13OqvVVsJ9Bss3xX"
      posts_today: 2
      google_sheets_source:
        enabled: true
        worksheet_name: "都内メンエス"
    - account_id: "hinataMaking"
      consumer_key: "dAWrjWZ9B3JPLitFAppAqYYle"
      consumer_secret: "hYVBLgMLvi5FbGn8if6587M7yNVLN7uxG6U1yqezlaiN5s853S"
      access_token: "1790120446198689792-cTjrCAE1viby3LhpKl1wvnqj6JIM4W"
      access_token_secret: "blDTtMDxtTo1WgcR4AEtZ3cs8zq8aa0BXWRlv1luYCdfv"
      posts_today: 4
      google_sheets_source:
        enabled: true
        worksheet_name: "都内セクキャバ"

# キュレーションBot設定（将来使用予定）
curate_bot:
  enabled: false

# 分析Bot設定（将来使用予定）
analyze_bot:
  enabled: false

# ========================================
# 削除した不要な設定項目：
# ========================================
# - password: API認証のみ使用のため不要
# - default_user_agents: 現在使用されていない
# - notion: Notion連携は現在未使用
# - gemini_api: OCR機能は現在未使用
# - openai_api: 現在未使用
# - user_id_cache: X API使用に不要
# - curate_bot詳細設定: 現在無効化
# - posting_settings詳細: デフォルト値で動作
# - scheduler詳細設定: 現在schedule_posts.py で管理
# - gspread_ocr_llm_settings: 現在未使用
# - csv_to_notion_processor_settings: 現在未使用
