# InboundEngine 設定ファイル (簡素化版)
# 実際に使用されている機能のみ記載

common:
  log_level: "INFO"
  file_paths:
    google_key_file: "gspread-key.json"

# X API認証情報（auto_post_botで使用）
twitter_api:
  bearer_token: "AAAAAAAAAAAAAAAAAAAAAGcD2AEAAAAANOU1DRELP%2B5FrtPFxHr1AKLH2fY%3DGEQfzeDonlRmHsHBaCJsNPxz4XeSWV7fPcFpgkdHfEbk8adrT9"
  consumer_key: "Y1OPAGo4bnenKVaPg9c4v7ZZv"
  consumer_secret: "cCZ0KOSXzKO8dgvdeG5NK04XDSB6MsdcxcF3kC1wOSorPizGZ6"
  access_token: "1606864928232857600-SVJ1fDLaISNXwFA2amUnQeNHFONIur"
  access_token_secret: "Ft6NWOcBqF8V1rC3AI9W8HgWg2yRY81Y38utgijzfIqkP"

# 自動投稿Bot設定
auto_post_bot:
  slack_webhook_url: "https://hooks.slack.com/services/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"
  sheet_name: "投稿ストック"
  columns: ["ID", "投稿アカウント", "投稿タイプ", "最終投稿日時", "文字数", "本文", "画像/動画URL", "投稿済み回数"]
  twitter_accounts:
    - account_id: "jadiAngkat"
      email: "jptmarketing.takahashi@gmail.com"
      username: "jadiAngkat"
      password: "Wm3hMCUT"  # 参考用（現在はAPI認証のみ使用）
      consumer_key: "jYJ4jjagTLCB6paNYyd9WjRKx"
      consumer_secret: "tBb7kc4frNUbKzUW1fyZwKs7hPRyaqcP4YpmaT7vFSH2b7Giww"
      access_token: "1669425142764810240-Tsvn4ivYdo9NfP9d2EEPxEiVo2MU81"
      access_token_secret: "6s2wRZd7LjW6piCNopg3zvYgcIK82YB9LDCV6alhvGCRq"
      google_sheets_source:
        enabled: true
        worksheet_name: "都内メンエス"
    - account_id: "hinataHHHHHH"
      email: "takahashi.jumpei.nari@gmail.com"
      username: "hinataHHHHHH"
      password: "Wm3hMCUT"  # 参考用（現在はAPI認証のみ使用）
      consumer_key: "jYJ4jjagTLCB6paNYyd9WjRKx"
      consumer_secret: "tBb7kc4frNUbKzUW1fyZwKs7hPRyaqcP4YpmaT7vFSH2b7Giww"
      access_token: "1669425142764810240-Tsvn4ivYdo9NfP9d2EEPxEiVo2MU81"
      access_token_secret: "6s2wRZd7LjW6piCNopg3zvYgcIK82YB9LDCV6alhvGCRq"
      google_sheets_source:
        enabled: true
        worksheet_name: "都内セクキャバ"

# キュレーションBot設定（将来使用予定）
curate_bot:
  enabled: false  # 現在は無効化

# 分析Bot設定（将来使用予定）
analyze_bot:
  enabled: false  # 現在は無効化

# ========================================
# 削除した不要な設定項目：
# ========================================
# - default_user_agents: 現在使用されていない
# - notion: Notion連携は現在未使用
# - gemini_api: OCR機能は現在未使用
# - openai_api: 現在未使用
# - user_id_cache: X API使用に不要
# - curate_bot詳細設定: 現在無効化
# - posting_settings詳細: デフォルト値で動作
# - scheduler詳細設定: 現在schedule_posts.py で管理
# - gspread_ocr_llm_settings: 現在未使用
# - csv_to_notion_processor_settings: 現在未使用
