# InboundEngine 設定ファイル

common:
  log_level: "INFO"
  file_paths:
    google_key_file: "gspread-key.json"

# 自動投稿Bot設定
auto_post_bot:
  slack_webhook_url: "https://hooks.slack.com/services/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"  # Slack通知用Webhook URL
  sheet_name: "投稿ストック"
  columns: ["ID", "最終投稿日時", "文字数", "本文", "画像/動画URL", "投稿可能", "投稿済み回数"]
  
  google_sheets_source:
    enabled: true
    spreadsheet_id: "1lgCn5iAiFT9PSr3vA3Tp1SePe0g3B9Xe1ppsr8bn2FA"
    worksheet_name: "都内メンエス"

  posting_settings:
    posts_per_account: 5
    max_posts_per_account: 5
    max_post_count: 3
    min_interval_hours: 24
    post_interval_seconds: 10
  
  schedule_settings:
    start_hour: 10
    end_hour: 22
    min_interval_minutes: 10
    schedule_file: "logs/schedule.txt"
    executed_file: "logs/executed.txt"
  
  media_settings:
    download_timeout: 60
    error_message_max_length: 100
    temp_file_cleanup: true
  
  text_settings:
    thread_padding: 10
    content_preview_length: 50
  
  twitter_accounts:
    - account_id: "ZaikerLong"
      consumer_key: "xAPh3lRibyp8qEqhXSlCPi9ls"
      consumer_secret: "EtWUYJRfXw37ZQyVP5LwQog13xi2UV3FYRvSWmYx4OF5zhg22j"
      access_token: "1332761771279601672-QZXhMnpVtjEWecoLMM40QmPCENzY0x"
      access_token_secret: "ZySI4nVscSfMjdGGpcOyOYbvRGePF13OqvVVsJ9Bss3xX"
      google_sheets_source:
        enabled: true
        worksheet_name: "都内メンエス"
    - account_id: "hinataMaking"
      consumer_key: "dAWrjWZ9B3JPLitFAppAqYYle"
      consumer_secret: "hYVBLgMLvi5FbGn8if6587M7yNVLN7uxG6U1yqezlaiN5s853S"
      access_token: "1790120446198689792-cTjrCAE1viby3LhpKl1wvnqj6JIM4W"
      access_token_secret: "blDTtMDxtTo1WgcR4AEtZ3cs8zq8aa0BXWRlv1luYCdfv"
      google_sheets_source:
        enabled: true
        worksheet_name: "都内セクキャバ"

# キュレーションBot設定（将来使用予定）
curate_bot:
  enabled: false

# 分析Bot設定（将来使用予定）
analyze_bot:
  enabled: false

# ========================================
# 削除した不要な設定項目：
# ========================================
# - password: API認証のみ使用のため不要
# - default_user_agents: 現在使用されていない
# - notion: Notion連携は現在未使用
# - gemini_api: OCR機能は現在未使用
# - openai_api: 現在未使用
# - user_id_cache: X API使用に不要
# - curate_bot詳細設定: 現在無効化
# - posting_settings詳細: デフォルト値で動作
# - scheduler詳細設定: 現在schedule_posts.py で管理
# - gspread_ocr_llm_settings: 現在未使用
# - csv_to_notion_processor_settings: 現在未使用
