# InboundEngine 設定ファイル (簡素化版)
# 実際に使用されている機能のみ記載

common:
  log_level: "INFO"
  file_paths:
    google_key_file: "gspread-key.json"

# X API認証情報（auto_post_botで使用）
twitter_api:
  bearer_token: "AAAAAAAAAAAAAAAAAAAAAGcD2AEAAAAANOU1DRELP%2B5FrtPFxHr1AKLH2fY%3DGEQfzeDonlRmHsHBaCJsNPxz4XeSWV7fPcFpgkdHfEbk8adrT9"
  consumer_key: "Y1OPAGo4bnenKVaPg9c4v7ZZv"
  consumer_secret: "cCZ0KOSXzKO8dgvdeG5NK04XDSB6MsdcxcF3kC1wOSorPizGZ6"
  access_token: "1606864928232857600-SVJ1fDLaISNXwFA2amUnQeNHFONIur"
  access_token_secret: "Ft6NWOcBqF8V1rC3AI9W8HgWg2yRY81Y38utgijzfIqkP"

# 自動投稿Bot設定
auto_post_bot:
  slack_webhook_url: "https://hooks.slack.com/services/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"
  sheet_name: "投稿ストック"
  columns: ["ID", "最終投稿日時", "文字数", "本文", "画像/動画URL", "投稿可能", "投稿済み回数"]
  
  # 投稿制御設定
  posting_settings:
    posts_per_account: 1                    # 1アカウントあたりの投稿回数
    max_posts_per_account: 1                # 処理時の最大投稿数
    max_post_count: 3                       # 記事あたりの最大投稿回数
    min_interval_hours: 24                  # 最小投稿間隔（時間）
    post_interval_seconds: 10               # 投稿間の待機時間（秒）
  
  # スケジュール設定
  schedule_settings:
    start_hour: 10                          # 営業開始時間
    end_hour: 22                            # 営業終了時間
    min_interval_minutes: 10                # 最小投稿間隔（分）
    schedule_file: "logs/schedule.txt"      # スケジュールファイルパス
    executed_file: "logs/executed.txt"      # 実行済みファイルパス
  
  # メディア処理設定
  media_settings:
    download_timeout: 60                    # ダウンロードタイムアウト（秒）
    error_message_max_length: 100           # エラーメッセージ最大文字数
    temp_file_cleanup: true                 # 一時ファイル自動削除
  
  # テキスト処理設定
  text_settings:
    thread_padding: 10                      # ツリー投稿時の文字数余裕
    content_preview_length: 50              # プレビュー表示文字数
  
  twitter_accounts:
    - account_id: "jadiAngkat"
      email: "jptmarketing.takahashi@gmail.com"
      username: "jadiAngkat"
      consumer_key: "jYJ4jjagTLCB6paNYyd9WjRKx"
      consumer_secret: "tBb7kc4frNUbKzUW1fyZwKs7hPRyaqcP4YpmaT7vFSH2b7Giww"
      access_token: "1669425142764810240-Tsvn4ivYdo9NfP9d2EEPxEiVo2MU81"
      access_token_secret: "6s2wRZd7LjW6piCNopg3zvYgcIK82YB9LDCV6alhvGCRq"
      google_sheets_source:
        enabled: true
        worksheet_name: "都内メンエス"
    - account_id: "hinataHHHHHH"
      email: "takahashi.jumpei.nari@gmail.com"
      username: "hinataHHHHHH"
      consumer_key: "jYJ4jjagTLCB6paNYyd9WjRKx"
      consumer_secret: "tBb7kc4frNUbKzUW1fyZwKs7hPRyaqcP4YpmaT7vFSH2b7Giww"
      access_token: "1669425142764810240-Tsvn4ivYdo9NfP9d2EEPxEiVo2MU81"
      access_token_secret: "6s2wRZd7LjW6piCNopg3zvYgcIK82YB9LDCV6alhvGCRq"
      google_sheets_source:
        enabled: true
        worksheet_name: "都内セクキャバ"

# キュレーションBot設定（将来使用予定）
curate_bot:
  enabled: false  # 現在は無効化

# 分析Bot設定（将来使用予定）
analyze_bot:
  enabled: false  # 現在は無効化

# ========================================
# 削除した不要な設定項目：
# ========================================
# - password: API認証のみ使用のため不要
# - default_user_agents: 現在使用されていない
# - notion: Notion連携は現在未使用
# - gemini_api: OCR機能は現在未使用
# - openai_api: 現在未使用
# - user_id_cache: X API使用に不要
# - curate_bot詳細設定: 現在無効化
# - posting_settings詳細: デフォルト値で動作
# - scheduler詳細設定: 現在schedule_posts.py で管理
# - gspread_ocr_llm_settings: 現在未使用
# - csv_to_notion_processor_settings: 現在未使用
