name: Generate Daily Post Schedule

on:
  schedule:
    # 毎日日本時間9時に実行 (UTCで0時)
    - cron: '0 0 * * *'
  workflow_dispatch: # 手動実行を許可

jobs:
  generate-schedule-job: # ジョブ名を変更
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set APP_CONFIG_JSON Environment Variable from Secret
      env:
        APP_CONFIG_CONTENT: ${{ secrets.APP_CONFIG_JSON }}
      run: |
        if [ -z "${APP_CONFIG_CONTENT}" ]; then
          echo "::error::Secret APP_CONFIG_JSON is not set or is empty."
          exit 1
        fi
        delimiter=$(uuidgen)
        echo "APP_CONFIG_JSON<<${delimiter}" >> $GITHUB_ENV
        echo "${APP_CONFIG_CONTENT}" >> $GITHUB_ENV
        echo "${delimiter}" >> $GITHUB_ENV
        echo "APP_CONFIG_JSON environment variable has been set."

    - name: Generate daily schedule
      run: python main.py --generate-schedule

    - name: Discord Notification on Failure
      if: failure()
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL_FAILURE }} # 失敗通知用
        content: "❌ Schedule Generation Failed: ${{ github.workflow }} / ${{ github.job }} on ${{ github.ref }}"

    # - name: Discord Notification on Success (オプション: 必要に応じて有効化)
    #   if: success()
    #   uses: tsickert/discord-webhook@v5.3.0
    #   with:
    #     webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
    #     content: "✅ GitHub Actions Workflow Succeeded: ${{ github.workflow }} / ${{ github.job }} on ${{ github.ref }}" 