name: Process Scheduled Posts

on:
  # schedule:
    # 例: 15分ごとに実行
    # - cron: '*/15 * * * *'
  workflow_dispatch: # 手動実行も可能にしておくとデバッグに便利

jobs:
  process-posts-job:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
    # 同時実行を防ぐ (オプション)
    concurrency:
      group: ${{ github.workflow }}-process
      cancel-in-progress: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Set APP_CONFIG_JSON Environment Variable from Secret
      env:
        APP_CONFIG_CONTENT: ${{ secrets.APP_CONFIG_JSON }}
      run: |
        if [ -z "${APP_CONFIG_CONTENT}" ]; then
          echo "::error::Secret APP_CONFIG_JSON is not set or is empty."
          exit 1
        fi
        # 一時ファイルとして書き出す
        mkdir -p .github/secrets
        echo "${APP_CONFIG_CONTENT}" > .github/secrets/app_config.json
        echo "Secret APP_CONFIG_JSON has been written to .github/secrets/app_config.json"

    - name: Execute post processing
      id: post_process # IDを追加して後で参照できるようにする
      run: python main.py --process --config .github/secrets/app_config.json
    
    - name: Extract Discord Webhook URL for failure notification
      # 投稿プロセスが失敗した場合にのみ実行
      if: failure() && steps.post_process.outcome == 'failure'
      id: extract_discord_url
      run: |
        # config.pyのget_discord_webhook_urlの実装に合わせて "common.discord.webhook_url" をキーとして抽出
        URL=$(jq -r '.common.discord.webhook_url' .github/secrets/app_config.json)
        if [ -z "$URL" ] || [ "$URL" == "null" ]; then
          echo "::warning::Discord Webhook URL not found in APP_CONFIG_JSON. Failure notification cannot be sent."
          echo "webhook_url=" >> $GITHUB_OUTPUT
        else
          echo "webhook_url=$URL" >> $GITHUB_OUTPUT
        fi

    - name: Discord Notification on Failure
      if: failure() # 失敗した場合に実行する
      uses: tsickert/discord-webhook@v5.3.0
      with:
        # 抽出したURLを使い、なければ何も送らない
        webhook-url: ${{ steps.extract_discord_url.outputs.webhook_url }}
        content: "❌ Post Processing Failed: ${{ github.workflow }} / ${{ github.job }} on ${{ github.ref }}" 